// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=../mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/sleepy-moon-cake/golang_transform_url/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockURLService is a mock of URLService interface.
type MockURLService struct {
	ctrl     *gomock.Controller
	recorder *MockURLServiceMockRecorder
	isgomock struct{}
}

// MockURLServiceMockRecorder is the mock recorder for MockURLService.
type MockURLServiceMockRecorder struct {
	mock *MockURLService
}

// NewMockURLService creates a new mock instance.
func NewMockURLService(ctrl *gomock.Controller) *MockURLService {
	mock := &MockURLService{ctrl: ctrl}
	mock.recorder = &MockURLServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLService) EXPECT() *MockURLServiceMockRecorder {
	return m.recorder
}

// Batch mocks base method.
func (m *MockURLService) Batch(ctx context.Context, shorURLBatch []model.ShortenURLBatchRequest) ([]model.ShortenURLBatchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Batch", ctx, shorURLBatch)
	ret0, _ := ret[0].([]model.ShortenURLBatchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Batch indicates an expected call of Batch.
func (mr *MockURLServiceMockRecorder) Batch(ctx, shorURLBatch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Batch", reflect.TypeOf((*MockURLService)(nil).Batch), ctx, shorURLBatch)
}

// CreateShortURL mocks base method.
func (m *MockURLService) CreateShortURL(ctx context.Context, str string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShortURL", ctx, str)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShortURL indicates an expected call of CreateShortURL.
func (mr *MockURLServiceMockRecorder) CreateShortURL(ctx, str any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShortURL", reflect.TypeOf((*MockURLService)(nil).CreateShortURL), ctx, str)
}

// DeleteBatchUrl mocks base method.
func (m *MockURLService) DeleteBatchUrl(ctx context.Context, shotUrls []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBatchUrl", ctx, shotUrls)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBatchUrl indicates an expected call of DeleteBatchUrl.
func (mr *MockURLServiceMockRecorder) DeleteBatchUrl(ctx, shotUrls any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBatchUrl", reflect.TypeOf((*MockURLService)(nil).DeleteBatchUrl), ctx, shotUrls)
}

// GetStats mocks base method.
func (m *MockURLService) GetStats(arg0 context.Context) (model.URLStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", arg0)
	ret0, _ := ret[0].(model.URLStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockURLServiceMockRecorder) GetStats(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockURLService)(nil).GetStats), arg0)
}

// GetURLByCode mocks base method.
func (m *MockURLService) GetURLByCode(ctx context.Context, code string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURLByCode", ctx, code)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURLByCode indicates an expected call of GetURLByCode.
func (mr *MockURLServiceMockRecorder) GetURLByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURLByCode", reflect.TypeOf((*MockURLService)(nil).GetURLByCode), ctx, code)
}

// GetUserShortUrls mocks base method.
func (m *MockURLService) GetUserShortUrls(ctx context.Context) ([]model.ShortenURLRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserShortUrls", ctx)
	ret0, _ := ret[0].([]model.ShortenURLRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserShortUrls indicates an expected call of GetUserShortUrls.
func (mr *MockURLServiceMockRecorder) GetUserShortUrls(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserShortUrls", reflect.TypeOf((*MockURLService)(nil).GetUserShortUrls), ctx)
}

// Ping mocks base method.
func (m *MockURLService) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockURLServiceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockURLService)(nil).Ping), ctx)
}
