package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

// StructInfo собирает метаданные структуры для генерации метода Reset
type StructInfo struct {
	Name   string
	Fields []*ast.Field
}

func main() {
	// 1. Настройка конфигурации для рекурсивного сканирования всего проекта
	cfg := &packages.Config{
		Mode: packages.NeedSyntax | packages.NeedName | packages.NeedFiles,
		Fset: token.NewFileSet(),
	}

	// Любое имя пакета "./..." заставит Go рекурсивно пройти от текущей папки и ниже
	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		log.Fatalf("Ошибка загрузки пакетов: %v", err)
	}

	// 2. Итерируемся по всем найденным пакетам проекта
	for _, pkg := range pkgs {
		if len(pkg.Syntax) == 0 {
			continue
		}

		var targetStructs []StructInfo
		var packageDir string

		// Сканируем каждый файл в текущем пакете
		for i, fileAST := range pkg.Syntax {
			if packageDir == "" && len(pkg.GoFiles) > i {
				packageDir = filepath.Dir(pkg.GoFiles[i])
			}

			// Пропускаем уже сгенерированные ранее файлы, чтобы не зацикливаться
			if filepath.Base(pkg.GoFiles[i]) == "reset.gen.go" {
				continue
			}

			// Быстрая проверка (Fast-Fail): если маркера нет в комментариях файла, пропускаем его
			hasMarker := false
			for _, c := range fileAST.Comments {
				if strings.Contains(c.Text(), "generate:reset") {
					hasMarker = true
					break
				}
			}
			if !hasMarker {
				continue
			}

			// Точный поиск структур с комментарием // generate:reset
			ast.Inspect(fileAST, func(n ast.Node) bool {
				genDecl, ok := n.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					return true
				}

				// Проверяем комментарий Doc над блоком объявления типа
				if genDecl.Doc != nil && strings.Contains(genDecl.Doc.Text(), "generate:reset") {
					for _, spec := range genDecl.Specs {
						if typeSpec, ok := spec.(*ast.TypeSpec); ok {
							if structType, ok := typeSpec.Type.(*ast.StructType); ok {
								targetStructs = append(targetStructs, StructInfo{
									Name:   typeSpec.Name.Name,
									Fields: structType.Fields.List,
								})
							}
						}
					}
				}
				return true
			})
		}

		// 3. Если в пакете найдены целевые структуры, генерируем для них файл
		if len(targetStructs) > 0 && packageDir != "" {
			err := generateResetFile(pkg.Name, packageDir, targetStructs)
			if err != nil {
				log.Fatalf("Ошибка генерации для пакета %s: %v", pkg.Name, err)
			}
			fmt.Printf("Успешно сгенерирован reset.gen.go для пакета: %s\n", pkg.Name)
		}
	}
}

// generateResetFile формирует текст файла reset.gen.go, форматирует его и записывает на диск
func generateResetFile(packageName, outputDir string, structs []StructInfo) error {
	var buf bytes.Buffer

	// Пишем шапку файла
	buf.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", packageName))

	// Генерируем метод Reset() для каждой структуры
	for _, st := range structs {
		buf.WriteString(fmt.Sprintf("func (r *%s) Reset() {\n", st.Name))

		for _, field := range st.Fields {
			for _, fieldName := range field.Names {
				name := fieldName.Name
				genFieldReset(&buf, name, field.Type)
			}
		}

		buf.WriteString("}\n\n")
	}

	// Форматируем код через go/format (чтобы расставить отступы и табы)
	formattedCode, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("ошибка форматирования кода: %w", err)
	}

	// Записываем результат в файл пакета
	outputPath := filepath.Join(outputDir, "reset.gen.go")
	return os.WriteFile(outputPath, formattedCode, 0644)
}

// genFieldReset анализирует тип поля и пишет соответствующую логику сброса в буфер
func genFieldReset(buf *bytes.Buffer, name string, expr ast.Expr) {
	switch t := expr.(type) {

	case *ast.Ident: // Примитивные типы (int, string, bool, etc.)
		switch t.Name {
		case "string":
			buf.WriteString(fmt.Sprintf("\tr.%s = \"\"\n", name))
		case "bool":
			buf.WriteString(fmt.Sprintf("\tr.%s = false\n", name))
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64", "uintptr", "rune", "byte":
			buf.WriteString(fmt.Sprintf("\tr.%s = 0\n", name))
		case "float32", "float64":
			buf.WriteString(fmt.Sprintf("\tr.%s = 0.0\n", name))
		default:
			// Вложенная структура без указателя (например, field MyStruct)
			// Вызываем метод Reset(), если он у нее предполагается по условию задания
			buf.WriteString(fmt.Sprintf("\tr.%s.Reset()\n", name))
		}

	case *ast.ArrayType: // Слайсы (массивы фиксированной длины t.Len == nil проверяются так же)
		if t.Len == nil {
			// Слайс: обрезаем длину до 0 по условию задания (с сохранением капа)
			buf.WriteString(fmt.Sprintf("\tr.%s = r.%s[:0]\n", name, name))
		} else {
			// Массив фиксированной длины [4]int — зануляем через пустой литерал типа
			// (опционально, в условии просили только слайсы, но полезно для стабильности)
			buf.WriteString(fmt.Sprintf("\tr.%s = %s{}\n", name, name))
		}

	case *ast.MapType: // Мапы
		// Очищаем через встроенную функцию clear() (доступна с Go 1.21)
		buf.WriteString(fmt.Sprintf("\tclear(r.%s)\n", name))

	case *ast.StarExpr: // Указатели (*int, *MyStruct, etc.)
		buf.WriteString(fmt.Sprintf("\tif r.%s != nil {\n", name))
		// Проверяем, на что указывает этот указатель
		switch pType := t.X.(type) {
		case *ast.Ident:
			if isPrimitive(pType.Name) {
				// Если указатель на примитив, сбрасываем значение под ним к дефолту
				buf.WriteString(fmt.Sprintf("\t\t*r.%s = %s\n", name, getPrimitiveDefault(pType.Name)))
			} else {
				// Если указатель на структуру, вызываем её метод Reset()
				buf.WriteString(fmt.Sprintf("\t\tr.%s.Reset()\n", name))
			}
		default:
			// Для сложных указателей (указатель на мапу/слайс) рекурсивно вызываем логику
			// Но пишем без префикса "r.", так как мы уже внутри разыменования/проверки
			buf.WriteString(fmt.Sprintf("\t\t// Сложный указатель\n"))
		}
		buf.WriteString("\t}\n")

	case *ast.SelectorExpr: // Типы из других пакетов (например, time.Time)
		// Для внешних структур вызываем Reset(), если она им обладает
		buf.WriteString(fmt.Sprintf("\tr.%s.Reset()\n", name))
	}
}

// Вспомогательная функция для проверки примитивов
func isPrimitive(name string) bool {
	switch name {
	case "string", "bool", "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "float32", "float64", "byte", "rune":
		return true
	}
	return false
}

// Вспомогательная функция для получения нулевого значения в виде строки
func getPrimitiveDefault(name string) string {
	switch name {
	case "string":
		return `""`
	case "bool":
		return "false"
	case "float32", "float64":
		return "0.0"
	default:
		return "0"
	}
}
