package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

// StructInfo хранит проверенную информацию о типах от go/types
type StructInfo struct {
	Name   string
	Fields []FieldInfo
}

type FieldInfo struct {
	Name string
	Type types.Type
}

func main() {
	// 1. Включаем NeedTypes и NeedTypesInfo.
	cfg := &packages.Config{
		Mode: packages.NeedSyntax | packages.NeedName | packages.NeedFiles | packages.NeedTypes | packages.NeedTypesInfo,
		Fset: token.NewFileSet(),
	}

	// Загружаем проект
	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		log.Fatalf("Ошибка загрузки пакетов: %v", err)
	}

	// 2. Итерируемся по пакетам
	for _, pkg := range pkgs {
		if len(pkg.Errors) > 0 {
			log.Printf("Предупреждение: ошибки в пакете %s: %v", pkg.Name, pkg.Errors)
		}
		if len(pkg.Syntax) == 0 {
			continue
		}

		var targetStructs []StructInfo
		var packageDir string

		// Сканируем каждый файл в текущем пакете
		for i, fileAST := range pkg.Syntax {
			if packageDir == "" && len(pkg.GoFiles) > i {
				packageDir = filepath.Dir(pkg.GoFiles[i])
			}

			// Пропускаем уже сгенерированные ранее файлы, чтобы не зацикливаться
			if filepath.Base(pkg.GoFiles[i]) == "reset.gen.go" {
				continue
			}

			// Быстрая проверка (Fast-Fail): если маркера нет в комментариях файла, пропускаем его
			hasMarker := false
			for _, c := range fileAST.Comments {
				if strings.Contains(c.Text(), "generate:reset") {
					hasMarker = true
					break
				}
			}
			if !hasMarker {
				continue
			}

			// Точный поиск структур с комментарием // generate:reset
			ast.Inspect(fileAST, func(n ast.Node) bool {
				genDecl, ok := n.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					return true
				}

				if genDecl.Doc != nil && strings.Contains(genDecl.Doc.Text(), "generate:reset") {
					for _, spec := range genDecl.Specs {
						typeSpec, ok := spec.(*ast.TypeSpec)
						if !ok {
							continue
						}

						obj := pkg.TypesInfo.Defs[typeSpec.Name]
						if obj == nil {
							continue
						}

						// Проверяем, что это именно Named тип (имеющий имя)
						named, ok := obj.Type().(*types.Named)
						if !ok {
							continue
						}

						// Достаем структуру, которая скрывается под этим именем
						structType, ok := named.Underlying().(*types.Struct)
						if !ok {
							continue
						}

						// Собираем поля, используя строго типизированный API компилятора
						var fields []FieldInfo
						for j := 0; j < structType.NumFields(); j++ {
							field := structType.Field(j)

							// Пропускаем встроенные (embedded) безымянные поля, если это необходимо,
							// либо берем их имя типа как имя поля.
							fields = append(fields, FieldInfo{
								Name: field.Name(),
								Type: field.Type(),
							})
						}

						targetStructs = append(targetStructs, StructInfo{
							Name:   typeSpec.Name.Name,
							Fields: fields,
						})
					}
				}
				return true
			})
		}

		// 3. Если в пакете найдены целевые структуры, генерируем для них файл
		if len(targetStructs) > 0 && packageDir != "" {
			err := generateResetFile(pkg.Name, packageDir, targetStructs)
			if err != nil {
				log.Fatalf("Ошибка генерации для пакета %s: %v", pkg.Name, err)
			}
			fmt.Printf("Успешно сгенерирован reset.gen.go для пакета: %s\n", pkg.Name)
		}
	}
}

func generateResetFile(packageName, outputDir string, structs []StructInfo) error {
	var buf bytes.Buffer

	// Пишем шапку файла
	buf.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", packageName))

	// Генерируем метод Reset() для каждой структуры
	for _, st := range structs {
		buf.WriteString(fmt.Sprintf("func (r *%s) Reset() {\n", st.Name))

		for _, field := range st.Fields {
			genFieldReset(&buf, field.Name, field.Type)
		}

		buf.WriteString("}\n\n")
	}

	// Форматируем код через go/format (чтобы расставить отступы и табы)
	formattedCode, err := format.Source(buf.Bytes())
	if err != nil {
		// Для отладки полезно вывести сырой код, если форматирование упало
		os.WriteFile(filepath.Join(outputDir, "reset.error.go"), buf.Bytes(), 0644)
		return fmt.Errorf("ошибка форматирования кода: %w", err)
	}

	// Записываем результат в файл пакета
	outputPath := filepath.Join(outputDir, "reset.gen.go")
	return os.WriteFile(outputPath, formattedCode, 0644)
}

// genFieldReset анализирует реальный тип (Underlying) и генерирует код сброса
func genFieldReset(buf *bytes.Buffer, name string, t types.Type) {
	// Получаем базовый тип (раскрывает кастомные типы вроде type MyInt int -> int)
	underlying := t.Underlying()

	switch ut := underlying.(type) {

	case *types.Basic: // Примитивные типы (включая кастомные типы на их основе)
		info := ut.Info()
		if info&types.IsString != 0 {
			buf.WriteString(fmt.Sprintf("\tr.%s = \"\"\n", name))
		} else if info&types.IsBoolean != 0 {
			buf.WriteString(fmt.Sprintf("\tr.%s = false\n", name))
		} else if info&types.IsFloat != 0 {
			buf.WriteString(fmt.Sprintf("\tr.%s = 0.0\n", name))
		} else if info&types.IsInteger != 0 {
			buf.WriteString(fmt.Sprintf("\tr.%s = 0\n", name))
		}

	case *types.Slice: // Слайсы (даже если это кастомный тип вроде type MySlice []int)
		// Срезаем длину до 0 с сохранением капа (r.Field = r.Field[:0])
		buf.WriteString(fmt.Sprintf("\tr.%s = r.%s[:0]\n", name, name))

	case *types.Map: // Мапы
		// Очищаем через clear(r.Field)
		buf.WriteString(fmt.Sprintf("\tclear(r.%s)\n", name))

	case *types.Pointer: // Указатели (*int, *Struct, etc.)
		buf.WriteString(fmt.Sprintf("\tif r.%s != nil {\n", name))

		// Смотрим, на что указывает указатель (его базовый тип)
		elemUnderlying := ut.Elem().Underlying()

		switch et := elemUnderlying.(type) {
		case *types.Basic:
			// Если указатель на примитив, безопасно зануляем значение под ним
			info := et.Info()
			if info&types.IsString != 0 {
				buf.WriteString(fmt.Sprintf("\t\t*r.%s = \"\"\n", name))
			} else if info&types.IsBoolean != 0 {
				buf.WriteString(fmt.Sprintf("\t\t*r.%s = false\n", name))
			} else if info&types.IsFloat != 0 {
				buf.WriteString(fmt.Sprintf("\t\t*r.%s = 0.0\n", name))
			} else if info&types.IsInteger != 0 {
				buf.WriteString(fmt.Sprintf("\t\t*r.%s = 0\n", name))
			}
		case *types.Struct:
			// Если указатель на структуру, вызываем её метод Reset()
			buf.WriteString(fmt.Sprintf("\t\tr.%s.Reset()\n", name))
		default:
			// На случай указателей на сложные типы (указатель на мапу/слайс)
			buf.WriteString(fmt.Sprintf("\t\t// Сложный тип под указателем\n"))
		}
		buf.WriteString("\t}\n")

	case *types.Struct: // Вложенная структура без указателя
		// Если структура имеет имя (не анонимная), у неё вызывается её собственный Reset
		if _, ok := t.(*types.Named); ok {
			buf.WriteString(fmt.Sprintf("\tr.%s.Reset()\n", name))
		} else {
			// Для анонимных структур (например, Field struct{A int}) зануляем литералом
			buf.WriteString(fmt.Sprintf("\tr.%s = %s{}\n", name, t.String()))
		}

	case *types.Interface: // Интерфейсы (например, interface{} или any)
		// Интерфейсы сбрасываются в nil
		buf.WriteString(fmt.Sprintf("\tr.%s = nil\n", name))
	}
}
