// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package config

type ConfigMergerImpl struct{}

func (c *ConfigMergerImpl) Update(source *Config, target *Config) {
	if source != nil {
		if source.ServerAddress != "" {
			target.ServerAddress = source.ServerAddress
		}
		if source.GRPCServerAddress != "" {
			target.GRPCServerAddress = source.GRPCServerAddress
		}
		if source.BaseURLAddress != "" {
			target.BaseURLAddress = source.BaseURLAddress
		}
		if source.LoggerLevel != "" {
			target.LoggerLevel = source.LoggerLevel
		}
		if source.FileStoragePath != "" {
			target.FileStoragePath = source.FileStoragePath
		}
		if source.DatabaseDSN != "" {
			target.DatabaseDSN = source.DatabaseDSN
		}
		if source.AuditFile != "" {
			target.AuditFile = source.AuditFile
		}
		if source.AuditURL != "" {
			target.AuditURL = source.AuditURL
		}
		if source.Secure != false {
			target.Secure = source.Secure
		}
		if source.ConfigFilePath != "" {
			target.ConfigFilePath = source.ConfigFilePath
		}
		if source.TrustedSubnet != "" {
			target.TrustedSubnet = source.TrustedSubnet
		}
	}
}
